"""
Standalone report generator — run AFTER pytest completes.
Reads selenium_model/test_results.json and runs audit, then produces:
  - selenium_model/MASTER_TEST_AUDIT_REPORT.xlsx
  - selenium_model/FINAL_AUDIT_REPORT.md
"""
import sys
import json
import time
from pathlib import Path

project_root = str(Path(__file__).resolve().parent.parent)
if project_root not in sys.path:
    sys.path.insert(0, project_root)

def main():
    results_file = Path("selenium_model/test_results.json")
    test_results = []
    if results_file.exists():
        with open(results_file, "r", encoding="utf-8") as f:
            test_results = json.load(f)
        print(f"Loaded {len(test_results)} test results from {results_file}")
    else:
        print("Warning: test_results.json not found — generating report with empty test data")

    print("Running static/live audit...")
    from selenium_model.audit_runner import AuditRunner
    runner = AuditRunner(base_url="http://localhost:5000")
    audit_results = runner.run_all_audits()

    print("Generating Excel workbook...")
    from selenium_model.report_generator import generate_report
    generate_report(test_results, audit_results)
    print("  ✅ MASTER_TEST_AUDIT_REPORT.xlsx created")

    # Markdown summary
    total = len(test_results)
    passed = sum(1 for t in test_results if t["status"] == "PASSED")
    failed = sum(1 for t in test_results if t["status"] == "FAILED")
    skipped = total - passed - failed
    cov_pct = round((passed / total) * 100, 2) if total else 0
    total_bugs = (len(audit_results["unused_files"]) + len(audit_results["dead_code"]) +
                  len(audit_results["accessibility"]) + len(audit_results["security"]))

    md = f"""# CampusAssist — Master QA & Audit Report

## Executive Summary

| Metric | Value |
|--------|-------|
| Project | CampusAssist Smart College Helpdesk |
| Scan Date | {time.strftime('%Y-%m-%d %H:%M:%S')} |
| Total Tests | {total} |
| Passed | {passed} |
| Failed | {failed} |
| Skipped | {skipped} |
| Coverage | {cov_pct}% |
| Bugs Found | {total_bugs} |

## Test Modules

| Module | Tests | Pass | Fail |
|--------|-------|------|------|
"""
    modules = {}
    for t in test_results:
        m = t["module"]
        if m not in modules:
            modules[m] = {"pass": 0, "fail": 0}
        if t["status"] == "PASSED":
            modules[m]["pass"] += 1
        else:
            modules[m]["fail"] += 1
    for mod, counts in sorted(modules.items()):
        total_m = counts["pass"] + counts["fail"]
        md += f"| {mod} | {total_m} | {counts['pass']} | {counts['fail']} |\n"

    md += f"""
## Key Findings

### Security ({len(audit_results['security'])} items)
"""
    for s in audit_results["security"]:
        md += f"- **[{s['severity']}]** {s['area']}: {s['observation']}\n"

    md += f"""
### Broken Links ({len(audit_results['broken_links'])} checked)
"""
    for b in audit_results["broken_links"]:
        md += f"- {b['url']} → {b['result']} ({b['code']})\n"

    md += f"""
### Accessibility ({len(audit_results['accessibility'])} findings)
"""
    for a in audit_results["accessibility"][:10]:
        md += f"- **[{a['severity']}]** {a['page']}: {a['issue']}\n"
    if len(audit_results["accessibility"]) > 10:
        md += f"- _(+ {len(audit_results['accessibility'])-10} more — see Excel sheet)_\n"

    md += """
## Deliverables

- `selenium_model/MASTER_TEST_AUDIT_REPORT.xlsx` — Full 15-sheet Excel workbook
- `selenium_model/html_report.html` — Pytest HTML execution report
- `selenium_model/screenshots/` — Pass/fail screenshots
- `selenium_model/browser_console.log` — Chrome JS console log
- `selenium_model/FINAL_AUDIT_REPORT.md` — This file

*Generated by CampusAssist QA Automation Suite*
"""
    with open("selenium_model/FINAL_AUDIT_REPORT.md", "w", encoding="utf-8") as f:
        f.write(md)
    print("  ✅ FINAL_AUDIT_REPORT.md created")
    print("\nAll deliverables ready in selenium_model/")

if __name__ == "__main__":
    main()
